baseURL = 'https://blog.abstractionjackson.com/'
languageCode = 'en-us'
title = 'Abscriptum Digitus'
theme = 'haven'

[params]
description = 'The personal blog of San Francisco software engineer Jackson Galan.'

[params.root]
url = 'https://abstractionjackson.com'
title = 'Abstraction Jackson'